apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "photo-agent.fullname" . }}-config
  labels:
    {{- include "photo-agent.labels" . | nindent 4 }}
data:
  app.yaml: |
    app:
      name: {{ .Values.config.app.name | quote }}
      port: {{ .Values.config.app.port | quote }}
      url: {{ .Values.config.app.url | quote }}
    jwt:
      secret: {{ .Values.config.jwt.secret | quote }}
      access_hours: {{ .Values.config.jwt.access_hours }}
    mysql:
      skip: {{ .Values.config.mysql.skip }}
      host: {{ .Values.config.mysql.host | quote }}
      port: {{ .Values.config.mysql.port | quote }}
      username: {{ .Values.config.mysql.username | quote }}
      password: {{ .Values.config.mysql.password | quote }}
      database: {{ .Values.config.mysql.database | quote }}
    gemini:
      api_key: {{ .Values.config.gemini.api_key | quote }}
      model: {{ .Values.config.gemini.model | quote }}
