apiVersion: v1
kind: Service
metadata:
  name: {{ include "photo-agent.fullname" . }}
  labels:
    {{- include "photo-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "photo-agent.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
